# -*- coding: utf-8 -*-
"""ABSTRACTION & ENCAPSULATION

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oqZgY0bRorE2WIS7Ie8fpemOvPOOr0LF
"""

# ============================================================
#     Encapsulation & Abstraction Assignment - Easy Solution
# ============================================================

from abc import ABC, abstractmethod

# ============================================================
# PART A - ENCAPSULATION
# ============================================================

# 1 BankAccount Class
class BankAccount:
    def __init__(self, balance=0):
        self.__balance = balance  # private

    def deposit(self, amount):
        self.__balance += amount
        print(f"Deposited {amount}. New balance: {self.__balance}")

    def withdraw(self, amount):
        if amount > self.__balance:
            print("Insufficient balance!")
        else:
            self.__balance -= amount
            print(f"Withdrawn {amount}. Remaining: {self.__balance}")

    def get_balance(self):
        print(f"Balance: {self.__balance}")

print("--- BankAccount ---")
acc = BankAccount(1000)
acc.deposit(500)
acc.withdraw(200)
acc.withdraw(2000)
acc.get_balance()


# 2 Student Class
class Student:
    def __init__(self):
        self.__marks = 0

    def set_marks(self, marks):
        if 0 <= marks <= 100:
            self.__marks = marks
            print(f"Marks set to: {self.__marks}")
        else:
            print("Invalid! Marks must be between 0 and 100.")

    def get_marks(self):
        print(f"Marks: {self.__marks}")

print("\n--- Student ---")
s = Student()
s.set_marks(85)
s.set_marks(150)
s.get_marks()


# 3 Password Manager
class PasswordManager:
    def __init__(self):
        self.__password = "default123"

    def set_password(self, new_password):
        self.__password = new_password
        print("Password updated successfully.")

    def check_password(self, password):
        if password == self.__password:
            print("Password is correct!")
        else:
            print("Wrong password!")

print("\n--- Password Manager ---")
pm = PasswordManager()
pm.set_password("mySecret@99")
pm.check_password("wrong")
pm.check_password("mySecret@99")


# 4 Employee Class
class Employee:
    def __init__(self, salary):
        self.__salary = salary

    def increase_salary(self, percent):
        if percent < 0:
            print("Percent cannot be negative!")
        else:
            self.__salary += self.__salary * percent / 100
            print(f"Salary after {percent}% increase: {self.__salary}")

    def get_salary(self):
        print(f"Salary: {self.__salary}")

print("\n--- Employee ---")
emp = Employee(50000)
emp.get_salary()
emp.increase_salary(10)
emp.increase_salary(-5)


# ============================================================
# PART B - ABSTRACTION
# ============================================================

# 5 Abstract Shape
class Shape(ABC):
    @abstractmethod
    def area(self):
        pass

class Rectangle(Shape):
    def __init__(self, l, w):
        self.l = l
        self.w = w
    def area(self):
        print(f"Rectangle Area: {self.l * self.w}")

class Circle(Shape):
    def __init__(self, r):
        self.r = r
    def area(self):
        print(f"Circle Area: {3.14 * self.r * self.r:.2f}")

print("\n--- Abstract Shape ---")
Rectangle(5, 3).area()
Circle(7).area()


# 6 Abstract Animal
class Animal(ABC):
    @abstractmethod
    def make_sound(self):
        pass

class Dog(Animal):
    def make_sound(self):
        print("Dog: Woof!")

class Cat(Animal):
    def make_sound(self):
        print("Cat: Meow!")

class Cow(Animal):
    def make_sound(self):
        print("Cow: Moo!")

print("\n--- Abstract Animal ---")
for animal in [Dog(), Cat(), Cow()]:
    animal.make_sound()


# 7 Abstract Vehicle
class Vehicle(ABC):
    @abstractmethod
    def start(self):
        pass
    @abstractmethod
    def stop(self):
        pass

class Car(Vehicle):
    def start(self):
        print("Car started")
    def stop(self):
        print("Car stopped")

class Bike(Vehicle):
    def start(self):
        print("Bike started")
    def stop(self):
        print("Bike stopped")

print("\n--- Abstract Vehicle ---")
Car().start(); Car().stop()
Bike().start(); Bike().stop()


# 8 Abstract Employee (Salary)
class EmployeeABC(ABC):
    @abstractmethod
    def calculate_salary(self):
        pass

class FullTimeEmployee(EmployeeABC):
    def __init__(self, monthly):
        self.monthly = monthly
    def calculate_salary(self):
        print(f"Full-Time Salary: {self.monthly} per month")

class PartTimeEmployee(EmployeeABC):
    def __init__(self, hours, rate):
        self.hours = hours
        self.rate = rate
    def calculate_salary(self):
        print(f"Part-Time Salary: {self.hours * self.rate} (hours x rate)")

print("\n--- Abstract Employee ---")
FullTimeEmployee(60000).calculate_salary()
PartTimeEmployee(80, 200).calculate_salary()


# ============================================================
# PART C - MIXED (Encapsulation + Abstraction)
# ============================================================

# 9 Payment System
class Payment(ABC):
    @abstractmethod
    def pay(self, amount):
        pass

class CreditCardPayment(Payment):
    def __init__(self, card_number):
        self.__card_number = card_number
    def pay(self, amount):
        print(f"Paid {amount} via Credit Card ending in {str(self.__card_number)[-4:]}")

class CashPayment(Payment):
    def pay(self, amount):
        print(f"Paid {amount} in Cash")

print("\n--- Payment System ---")
CreditCardPayment(1234567890123456).pay(5000)
CashPayment().pay(1000)


# 10 ATM Machine
class ATM:
    def __init__(self, balance):
        self.__balance = balance

    def deposit(self, amount):
        self.__balance += amount
        print(f"Deposited {amount}. Balance: {self.__balance}")

    def withdraw(self, amount):
        if amount > self.__balance:
            print("Insufficient funds!")
        else:
            self.__balance -= amount
            print(f"Withdrawn {amount}. Balance: {self.__balance}")

    def check_balance(self):
        print(f"Current Balance: {self.__balance}")

print("\n--- ATM Machine ---")
atm = ATM(10000)
atm.check_balance()
atm.deposit(2000)
atm.withdraw(5000)
atm.withdraw(20000)


# ============================================================
# THEORY ANSWERS
# ============================================================

print("""
--- Theory Answers ---

1. Encapsulation:
   Wrapping data (variables) and methods together in a class, and restricting
   direct access to private data. Access is only through defined methods.

2. Abstraction:
   Hiding complex implementation details and showing only essential features.
   Achieved using abstract classes and methods (ABC module).

3. Abstraction vs Encapsulation:
   - Encapsulation -> hides DATA (using private variables)
   - Abstraction   -> hides IMPLEMENTATION (using abstract methods)

4. Private Variable in Python:
   A variable with double underscore prefix e.g. __balance
   Cannot be accessed directly outside the class.

5. Abstract Class:
   A class that cannot be instantiated directly. It has at least one
   abstract method that must be overridden in child classes.

6. Can we create object of abstract class?
   NO. Python raises TypeError if we try.
   Reason: abstract methods have no implementation, so object would be incomplete.

7. Instance Attribute vs Class Attribute:
   - Instance: created in __init__, belongs to each object separately
   - Class: created outside __init__, shared by all objects
   - Access: instance -> self.attr  |  class -> ClassName.attr
   - If class attribute is changed -> it changes for ALL objects

8. Role of self:
   - self refers to the current object calling the method
   - Required so each object accesses its own data
   - Without self -> Python cannot find the object's attributes
   - self is NOT a keyword, just a strong convention

9. Encapsulation improves security:
   - Without it: any code can accidentally change important data (e.g. balance = -100)
   - Private variables prevent this by forcing use of controlled methods
   - Makes code easier to maintain because data access is centralized

10. Abstraction vs Encapsulation (real-life example - Car):
    - Encapsulation -> engine parts hidden inside car body (data hiding)
    - Abstraction   -> driver uses steering/pedals, does not know how engine works
    - Encapsulation -> hides DATA
    - Abstraction   -> hides IMPLEMENTATION
    - YES, both can and should be used together

11. What happens if:
    a) No __init__ defined:
       Python uses default constructor. Object is created but has no custom attributes.
    b) Access private variable directly (obj.__balance):
       AttributeError is raised. Python name-mangles it to _ClassName__balance.
    c) Create object of abstract class:
       TypeError: Cannot instantiate abstract class with abstract method.
""")